version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Update with your Dockerfile name
    restart: unless-stopped
    ports:
      - "5204:5204"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql-server
      - rabbitmq

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Agencija1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  rabbitmq-consumer:
    build:
      context: .
      dockerfile: ./RabbitMQConsumer/Dockerfile  # Update with the correct path
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
    networks:
      - discoverhscountrynet

networks:
  discoverhscountrynet:
    driver: bridge
