version: '3'
services:
  ecinemaconnect-sql:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"
    expose:
      - 1433
    networks:
      - ecinemaconnectnet
      
  ecinemaconnect-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=ecinemaconnect-sql,1433;Database=Cinema;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=cinemaconnectbusiness@gmail.com
      - SMTP_PASSWORD=bgtrwkasbwknntas
      - API_HOST=localhost
      - API_PORT=7125
    ports:
      - "7125:7125" 
    networks:
      - ecinemaconnectnet
    depends_on:
      - ecinemaconnect-sql
      - rabbitmq  
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecinemaconnectnet  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - ecinemaconnect-sql  
      
  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./RabbitMQConsumer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=cinemaconnectbusiness@gmail.com
      - SMTP_PASSWORD=bgtrwkasbwknntas
      - API_HOST=localhost
      - API_PORT=7125
    depends_on:
      - rabbitmq
      - ecinemaconnect-api
      - ecinemaconnect-sql
    networks:
      - ecinemaconnectnet
      
volumes:
  rabbitmq_data:
  
networks:
  ecinemaconnectnet:
    driver: bridge
