name: ecinemadesktop
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  http: ^0.13.3
  image_picker: ^0.8.4
  intl: ^0.18.1
  path_provider: ^2.1.2
  provider: ^6.0.0
  syncfusion_flutter_charts: ^24.2.5
  syncfusion_flutter_pdf: ^24.2.5
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cinema1.png
    - assets/noPhoto.jpg
